
== Building Applications

In this chapter we are going through the building of a _dueuno:elements_ application.

[[building-crud]]
=== CRUD
One of the most useful GUI pattern is the CRUD (Create, Read, Update, and Delete). It is based on the four basic operations available to work with persistent data and databases.

Applications are made of features, we register one to work with movies (See <<features>>).

.grails-app/init/BootStrap.groovy
[source,groovy]
----
class BootStrap {

    ApplicationService applicationService // <1>

    def init = { servletContext ->
        applicationService.init {
            registerFeature( // <2>
                    controller: 'movie',
                    icon: 'fa-film',
                    favourite: true,
            )
        }
    }
}
----
<1> See <<application>>
<2> See <<registerFeature>>

We are going to implement a simple database with https://gorm.grails.org/[GORM for Hibernate,window=_blank] on top of which we can build our GUI.

.grails-app/domain/TMovie.groovy
[source,groovy]
----
class TMovie implements MultiTenant<TMovie> {
    LocalDateTime dateCreated

    String title
    Integer released

    static hasMany = [actors: TActor]

    static constraints = {
    }
}
----

.grails-app/domain/TActor.groovy
[source,groovy]
----
class TActor implements MultiTenant<TActor> {
    LocalDateTime dateCreated

    String firstname
    String lastname

    static constraints = {
    }
}
----

To create a CRUD user interface we are going to implement a controller with the following actions. The business logic will be implemented into a service to keep it decoupled from the GUI.

.grails-app/controllers/BookController.groovy
[source,groovy]
----
@Secured(['ROLE_CAN_EDIT_MOVIES']) // <1>
class MovieController implements ElementsController { // <2>

    def index() {
        // will display a list of movies
    }

    def create() { //<3>
        // will display a form with the movie title
    }

    def onCreate() { // <3>
        // will create the movie record on the database
    }

    def edit() {
        // will display the details of a movie
    }

    def onEdit() {
        // will update the movie record on the database
    }

    def onDelete() {
        // will delete a movie record from the database
    }
}
----
<1> Only users with the `ROLE_CAN_EDIT_MOVIES` authority can access the actions in this controller.
<2> Implementing `ElementsController` the _dueuno:elements_ API will become available
<3> As a convention, all actions building and displaying a GUI are named after a verb or a name while all actions that execute a business logic are identified by a name starting with `on`.

We are going to use the `ContentList` content to list the records, the `ContentCreate` and `ContentEdit` contents to create a new record and edit an existing one (See <<contents>>).

.grails-app/controllers/BookController.groovy
[source,groovy]
----
@Secured(['ROLE_CAN_EDIT_MOVIES'])
class MovieController implements ElementsController {

    MovieService movieService // <1>

    def index() {
        def c = createContent(ContentList)
        c.table.with {
            filters.with {
                fold = false
                addField(
                        class: TextField,
                        id: 'find',
                        label: 'default.filters.text',
                        cols: 12,
                )
            }
            sortable = [
                    title: 'asc',
            ]
            columns = [
                    'title',
                    'released',
            ]

            body.eachRow { TableRow row, Map values ->
                // Do not execute slow operations here to avoid slowing down the table rendering
            }
        }

        def filters = c.table.filters.values
        c.table.body = movieService.list(filters, params)
        c.table.paginate = movieService.count(filters)

        display content: c
    }

    private buildForm(TMovie obj = null) {
        def c = obj
                ? createContent(ContentEdit)
                : createContent(ContentCreate)

        c.form.with {
            validate = TMovie
            addField(
                    class: TextField,
                    id: 'title',
            )
            addField(
                    class: NumberField,
                    id: 'released',
            )
        }

        if (obj) {
            c.form.values = obj
        }

        return c
    }

    def create() {
        def c = buildForm()
        display content: c, modal: true
    }

    def onCreate() {
        def obj = movieService.create(params)
        if (obj.hasErrors()) {
            display errors: obj
            return
        }

        display action: 'index'
    }

    def edit() {
        def obj = movieService.get(params.id)
        def c = buildForm(obj)
        display content: c, modal: true
    }

    def onEdit() {
        def obj = movieService.update(params)
        if (obj.hasErrors()) {
            display errors: obj
            return
        }

        display action: 'index'
    }

    def onDelete() {
        try {
            movieService.delete(params.id)
            display action: 'index'

        } catch (e) {
            display exception: e
        }
    }
}
----
<1> Service injection, see the implementation below

We will implement the database operations using https://gorm.grails.org/[GORM for Hibernate,window=_blank], the default Object Relational Mapper used by Grails.

.grails-app/services/MovieService.groovy
[source,groovy]
----
@CurrentTenant
class MovieService {

    private DetachedCriteria<TMovie> buildQuery(Map filters) {
        def query = TMovie.where {}

        if (filters.containsKey('id')) query = query.where { id == filters.id }

        if (filters.find) {
            String search = filters.find.replaceAll('\\*', '%')
            query = query.where {
                title =~ "%${search}%"
            }
        }

        // Add additional filters here

        return query
    }

    TMovie get(Serializable id) {
        // Add any relationships here (Eg. references to other DomainObjects or hasMany)
        Map fetch = [
                actors: 'join',
        ]

        return buildQuery(id: id).get(fetch: fetch)
    }

    List<TMovie> list(Map filters = [:], Map params = [:]) {
        if (!params.sort) params.sort = [dateCreated: 'asc']

        // Add single-sided relationships here (Eg. references to other Domain Objects)
        // DO NOT add hasMany relationships, you are going to have troubles with pagination
//        params.fetch = [
//                actors: 'join',
//        ]

        def query = buildQuery(filters)
        return query.list(params)
    }

    Integer count(Map filters = [:]) {
        def query = buildQuery(filters)
        return query.count()
    }

    TMovie create(Map args = [:]) {
        if (args.failOnError == null) args.failOnError = false

        TMovie obj = new TMovie(args)
        obj.save(flush: true, failOnError: args.failOnError)
        return obj
    }

    TMovie update(Map args = [:]) {
        Serializable id = ArgsException.requireArgument(args, 'id')
        if (args.failOnError == null) args.failOnError = false

        TMovie obj = get(id)
        obj.properties = args
        obj.save(flush: true, failOnError: args.failOnError)
        return obj
    }

    void delete(Serializable id) {
        TMovie obj = get(id)
        obj.delete(flush: true, failOnError: true)
    }
}
----

Run the application with gradle `bootRun`, you should be able to create, list, edit and delete movies.

=== Custom Contents
In the context of a controller action we can display to the user any content we need. To create a custom content we suggest creating a `ContentBlank` (See <<contents>>) adding the components wes need (See <<components>>).

