server:
  port: 9992
  servlet:
    context-path: /test

spring:
  h2:
    console:
      enabled: true
---
grails:
  controllers:
    upload:
      maxFileSize: 20000000
      maxRequestSize: 20000000

---
grails:
  profile: web
  codegen:
    defaultPackage: test.app
  gorm:
    reactor:
      # Whether to translate GORM events into Reactor events
      # Disabled by default for performance reasons
      events: false
info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
spring:
  jmx:
    unique-names: true
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false
  devtools:
    restart:
      additional-exclude:
        - '*.gsp'
        - '**/*.gsp'
        - '*.gson'
        - '**/*.gson'
        - 'logback.groovy'
        - '*.properties'
management:
  endpoints:
    enabled-by-default: false

---
grails:
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: singleton
  converters:
    encoding: UTF-8
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
management:
  endpoints:
    jmx:
      unique-names: true

---
hibernate:
  # Necessario per poter eseguire operazioni DB nei controller demo
  # Aggiunto in "elements"
  #allow_update_outside_transaction: true

  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false


# Add the following services from SAP BTP Cockpit
# - SAP HANA Cloud - hana
# - SAP HANA Cloud - relational-data-lake
# - SAP HANA Schemas & HDI Containers - schema (1)
#
# (1) Bind "schema" to the application, you will get something like this:
#
# {
#    "url": "jdbc:sap://host-code.hna1.prod-eu10.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=true&currentschema=USR_1234567890123456789012345",
#    "certificate": "-----BEGIN CERTIFICATE-----\nMIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBh\nMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3\nd3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD\nQTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAwMDAwMDBaMGExCzAJBgNVBAYTAlVT\nMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j\nb20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IENBMIIBIjANBgkqhkiG\n9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jvhEXLeqKTTo1eqUKKPC3eQyaKl7hLOllsB\nCSDMAZOnTjC3U/dDxGkAV53ijSLdhwZAAIEJzs4bg7/fzTtxRuLWZscFs3YnFo97\nnh6Vfe63SKMI2tavegw5BmV/Sl0fvBf4q77uKNd0f3p4mVmFaG5cIzJLv07A6Fpt\n43C/dxC//AH2hdmoRBBYMql1GNXRor5H4idq9Joz+EkIYIvUX7Q6hL+hqkpMfT7P\nT19sdl6gSzeRntwi5m3OFBqOasv+zbMUZBfHWymeMr/y7vrTC0LUq7dBMtoM1O/4\ngdW7jVg/tRvoSSiicNoxBN33shbyTApOB6jtSj1etX+jkMOvJwIDAQABo2MwYTAO\nBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbR\nTLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUw\nDQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/Esr\nhMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg\n06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJF\nPnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0ls\nYSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQk\nCAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4=\n-----END CERTIFICATE-----",
#    "database_id": ...,
#    "driver": "com.sap.db.jdbc.Driver",
#    "host": "host-code.hna1.prod-eu10.hanacloud.ondemand.com",
#    "password": "********",
#    "port": "443",
#    "schema": "USR_1234567890123456789012345",
#    "user": "USR_1234567890123456789012345"
# }
#
# Use that data to setup the DB. You can override the configuration form the application panel under
# the "User-Provided Variables" menu like this:
#
# dataSource.dialect: org.hibernate.dialect.HANAColumnStoreDialect
# dataSource.driverClassName: com.sap.db.jdbc.Driver
# dataSource.password: ********
# dataSource.url: jdbc:sap://host-code.hna1.prod-eu10.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=true&currentschema=USR_1234567890123456789012345
# dataSource.username: USR_1234567890123456789012345
#
# To drop the entire DB you can run this query and then run the results as a new query:
# SELECT 'DROP TABLE ' || TABLE_NAME || ' CASCADE;' AS DROP_ALL_TABLES
# FROM TABLES
# WHERE SCHEMA_NAME = 'USR_1234567890123456789012345';
#
dataSource:
  pooled: true
  jmxExport: true
  driverClassName: com.sap.db.jdbc.Driver
  dialect: org.hibernate.dialect.HANAColumnStoreDialect

environments:
  development:
    dataSource:
      dbCreate: update
      url: jdbc:sap://host-code.hna1.prod-eu10.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=true&currentschema=USR_1234567890123456789012345
      username: USR_1234567890123456789012345
      password: *

  test:
    dataSource:
      dbCreate: update
      url: jdbc:sap://host-code.hna1.prod-eu10.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=true&currentschema=USR_1234567890123456789012345
      username: USR_1234567890123456789012345
      password: *

  production:
    dataSource:
      dbCreate: update
      url: jdbc:sap://host-code.hna1.prod-eu10.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=true&currentschema=USR_1234567890123456789012345
      username: USR_1234567890123456789012345
      password: *
