server:
  port: 9992
  servlet:
    context-path: /test

spring:
  h2:
    console:
      enabled: true
---
grails:
  controllers:
    upload:
      maxFileSize: 20000000
      maxRequestSize: 20000000

---
grails:
  profile: web
  codegen:
    defaultPackage: test.app
  gorm:
    reactor:
      # Whether to translate GORM events into Reactor events
      # Disabled by default for performance reasons
      events: false
info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
spring:
  jmx:
    unique-names: true
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false
  devtools:
    restart:
      additional-exclude:
        - '*.gsp'
        - '**/*.gsp'
        - '*.gson'
        - '**/*.gson'
        - 'logback.groovy'
        - '*.properties'
management:
  endpoints:
    enabled-by-default: false

---
grails:
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: singleton
  converters:
    encoding: UTF-8
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
management:
  endpoints:
    jmx:
      unique-names: true

---
hibernate:
  # Necessario per poter eseguire operazioni DB nei controller demo
  # Aggiunto in "elements"
  #allow_update_outside_transaction: true

  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false

dataSource:
  pooled: true
  jmxExport: true
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  dialect: org.hibernate.dialect.SQLServer2008Dialect # for MS SQL server 2008 and onward
  #dialect: org.hibernate.dialect.SQLServerDialect #only for 2000 and 2005

  url: jdbc:sqlserver://localhost\instance_name:1433;databaseName=database_name
  username: sa
  password:

  properties:
    jmxEnabled: true
    initialSize: 5
    maxActive: 50
    minIdle: 5
    maxIdle: 25
    maxWait: 10000
    maxAge: 600000
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 60000
    validationQuery: "SELECT 1"
    validationQueryTimeout: 3
    validationInterval: 15000
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: false
    jdbcInterceptors: "ConnectionState;StatementCache(max=200)"
    defaultTransactionIsolation: 2

environments:
  development:
    grails:
      logging:
        jul:
          usebridge: true
      plugin:
        springsecurity:
          debug:
            useFilter: true
    dataSource:
      dbCreate: create-drop

  test:
    dataSource:
      dbCreate: update

  production:
    dataSource:
      dbCreate: update


